Repository brain-tec/account-invoice-reporting, pull requests merged in 2025-02, with the labels that each got.

#335 Syncing from upstream OCA/account-invoice-reporting (12.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .oca_hooks.cfg
Labels: 12.0

#336 Syncing from upstream OCA/account-invoice-reporting (13.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .oca_hooks.cfg
  .pre-commit-config.yaml
Labels: 13.0

#337 Syncing from upstream OCA/account-invoice-reporting (14.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .ruff.toml
Labels: 14.0

#338 Syncing from upstream OCA/account-invoice-reporting (15.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
Labels: 15.0

#339 Syncing from upstream OCA/account-invoice-reporting (16.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
Labels: 16.0

#340 Syncing from upstream OCA/account-invoice-reporting (17.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .ruff.toml
Labels: 17.0

#341 Syncing from upstream OCA/account-invoice-reporting (18.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .ruff.toml
  checklog-odoo.cfg
Labels: 18.0

#342 [FIX] account_invoice_report_grouped_by_picking: Display subtotals instead of totals
  account_invoice_report_grouped_by_picking/views/report_invoice.xml
Labels: 17.0.project_ev_734

#343 Syncing from upstream OCA/account-invoice-reporting (17.0)
  README.md
  account_invoice_report_grouped_by_picking/README.rst
  account_invoice_report_grouped_by_picking/__manifest__.py
  account_invoice_report_grouped_by_picking/static/description/index.html
  account_invoice_report_grouped_by_picking/views/report_invoice.xml
Labels: 17.0

#344 Syncing from upstream OCA/account-invoice-reporting (16.0)
  README.md
  account_invoice_report_product_sticker/README.rst
  account_invoice_report_product_sticker/__init__.py
  account_invoice_report_product_sticker/__manifest__.py
  account_invoice_report_product_sticker/i18n/account_invoice_report_product_sticker.pot
  account_invoice_report_product_sticker/i18n/es.po
  account_invoice_report_product_sticker/i18n/it.po
  account_invoice_report_product_sticker/models/__init__.py
  account_invoice_report_product_sticker/models/account_move.py
  account_invoice_report_product_sticker/models/res_config_settings.py
  account_invoice_report_product_sticker/readme/CONTRIBUTORS.md
  account_invoice_report_product_sticker/readme/DESCRIPTION.md
  account_invoice_report_product_sticker/readme/INSTALL.md
  account_invoice_report_product_sticker/readme/USAGE.md
  account_invoice_report_product_sticker/static/description/icon.png
  account_invoice_report_product_sticker/static/description/index.html
  account_invoice_report_product_sticker/tests/__init__.py
  account_invoice_report_product_sticker/tests/common.py
  account_invoice_report_product_sticker/tests/test_account_move.py
  account_invoice_report_product_sticker/views/account_move_view.xml
  account_invoice_report_product_sticker/views/report_invoice.xml
  account_invoice_report_product_sticker/views/res_config_settings_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_invoice_report_product_sticker/odoo/addons/account_invoice_report_product_sticker
  setup/account_invoice_report_product_sticker/setup.py
Labels: 16.0

#345 Syncing from upstream OCA/account-invoice-reporting (16.0)
  README.md
  account_invoice_report_product_sticker/README.rst
  account_invoice_report_product_sticker/__manifest__.py
  account_invoice_report_product_sticker/models/account_move.py
  account_invoice_report_product_sticker/static/description/index.html
Labels: 16.0

#346 Syncing from upstream OCA/account-invoice-reporting (16.0)
  README.md
  account_invoice_report_due_list/README.rst
  account_invoice_report_due_list/__manifest__.py
  account_invoice_report_due_list/static/description/index.html
  account_invoice_report_due_list/tests/test_invoice_report_due_list.py
  account_invoice_report_grouped_by_picking/README.rst
  account_invoice_report_grouped_by_picking/__manifest__.py
  account_invoice_report_grouped_by_picking/static/description/index.html
  account_invoice_report_grouped_by_picking/tests/test_account_invoice_group_picking.py
Labels: 16.0

#347 Syncing from upstream OCA/account-invoice-reporting (18.0)
  README.md
  account_invoice_line_sale_line_position/README.rst
  account_invoice_line_sale_line_position/__init__.py
  account_invoice_line_sale_line_position/__manifest__.py
  account_invoice_line_sale_line_position/i18n/account_invoice_line_sale_line_position.pot
  account_invoice_line_sale_line_position/i18n/de.po
  account_invoice_line_sale_line_position/i18n/es.po
  account_invoice_line_sale_line_position/i18n/it.po
  account_invoice_line_sale_line_position/models/__init__.py
  account_invoice_line_sale_line_position/models/account_invoice.py
  account_invoice_line_sale_line_position/pyproject.toml
  account_invoice_line_sale_line_position/readme/CONTRIBUTORS.md
  account_invoice_line_sale_line_position/readme/CREDITS.md
  account_invoice_line_sale_line_position/readme/DESCRIPTION.md
  account_invoice_line_sale_line_position/report/invoice_report.xml
  account_invoice_line_sale_line_position/static/description/icon.png
  account_invoice_line_sale_line_position/static/description/index.html
  account_invoice_line_sale_line_position/tests/__init__.py
  account_invoice_line_sale_line_position/tests/test_account_invoice_line_sale_line_position.py
  account_invoice_line_sale_line_position/views/account_move_views.xml
  setup/_metapackage/pyproject.toml
Labels: 18.0
